version: 2
jobs:
  build:
    docker:
        - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "requirements.txt" }}
              # fallback to using the lateest cache if no exact match is found
              - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv*bin/activate
            #pip install -r requirements.txt
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
      - run:
          name: run lint
          command: |
            . venv /bin/activate
            #python manage.py test
            make lint
            
      - store_artifacts:
          path: test-reports
          destination: test-reports